import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bustify - Book Bus Tickets Online | Fast & Easy Bus Booking',
  description: 'Book bus tickets online with Bustify. Compare prices with Abhibus, Redbus, and other providers. Fast, secure, and easy bus booking platform.',
  keywords: [
    'bustify',
    'bustify.in',
    'busify',
    'busify.in',
    'bus.in',
    'bus.com',
    'bus.com.in',
    'bus.com.in',
    'bustify',
    'abhibus',
    'redbus',
    'greenbus',
    'blackbus',
    'fast bus booking',
    'air conditioned bus',
    'luxury bus booking',
    'sleeper bus booking',
    'bus ticket price',
    'bus schedule',
    'bus routes',
    'bus timings',
    'bus booking app',
    'bus booking website',
    'bus booking platform',
    'bus booking service',
    'bus booking system',
    'bus booking software',
    'bus booking application',
    'bus booking website',
    'bus booking platform', 
    'NPTEL bus booking',
    'NPTEL bus ticket booking',
    'NPTEL bus schedule',
    'NPTEL bus routes',
    'NPTEL bus timings',
    'NPTEL bus ticket price',
    'NPTEL bus booking website',
    'NPTEL bus booking platform',
    'NPTEL bus booking service',
    'NPTEL bus booking system',
    'NPTEL bus booking software',
    'NPTEL bus booking application',
    'nptel bus booking',
    'nptel bus ticket booking',
    'nptel bus schedule',
    'nptel bus routes',
    'nptel bus timings',
    'nptel bus ticket price',
    'nptel bus booking website',
    'nptel bus booking platform',
    'nptel bus booking service',
    'nptel bus booking system',
    'nptel bus booking software',
    'nptel bus booking application',
    'nptel bus booking website',
    'nptel bus booking platform',
    
    
  ],
  openGraph: {
    title: 'Bustify - Book Bus Tickets Online | Fast & Easy Bus Booking',
    description: 'Book bus tickets online with Bustify. Compare prices with Abhibus, Redbus, and other providers. Fast, secure, and easy bus booking platform.',
    images: [
      {
        url: '/bustify-og.jpg',
        width: 1200,
        height: 630,
        alt: 'Bustify - Bus Booking Platform',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bustify - Book Bus Tickets Online | Fast & Easy Bus Booking',
    description: 'Book bus tickets online with Bustify. Compare prices with Abhibus, Redbus, and other providers. Fast, secure, and easy bus booking platform.',
    images: ['/bustify-twitter.jpg'],
  },
}; 